apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: nats
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  volumeMode: Filesystem