---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config-leaf
  namespace: nats
data:
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"
    http: 8222
    cluster {
      port: 6222
      connect_retries: 30
    }
    tls: {
    verify:  true
    ca_file: /etc/edge-nats-server-tls/ca.crt
    cert_file: /etc/edge-nats-server-tls/tls.crt
    key_file: /etc/edge-nats-server-tls/tls.key
    }
    leafnodes {
      remotes = [ 
        { 
          url: "nats-leaf://nats.nats.svc:7422"
          tls: {
            verify:   true
            cert_file: "/etc/nats-streaming-leaf-tls/tls.crt"
            key_file: "/etc/nats-streaming-leaf-tls/tls.key"
            ca_file: "/etc/nats-streaming-leaf-tls/ca.crt"
          }
        },
     ]
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nats-leaf
  namespace: nats
  labels:
    app: nats-leaf
spec:
  selector:
    app: nats
  type: NodePort
  ports:
  - name: client
    port: 4222
    nodePort: 31578
  - name: monitor
    port: 8222
  - name: metrics
    port: 7777
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nats-leaf
  namespace: nats
  labels:
    app: nats-leaf
spec:
  selector:
    matchLabels:
      app: nats-leaf
  replicas: 1
  template:
    metadata:
      labels:
        app: nats-leaf
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
      #nodeSelector:
        #kubernetes.io/hostname: "a81166f065-edge-idxc.novalocal"
        #kubernetes.io/hostname: "a81166f065-gjyn2-lkss-1.novalocal"
      # Common volumes for the containers
      volumes:
      - name: pid
        emptyDir: {}
      - name: config-volume
        configMap:
          name: nats-config-leaf
      - name: edge-nats-server-tls
        secret:
          defaultMode: 420
          secretName: edge-nats-server-tls
      - name: nats-streaming-leaf-tls
        secret:
          defaultMode: 420
          secretName: nats-streaming-leaf-tls
      # Required to be able to HUP signal and apply config reload
      # to the server without restarting the pod.
      shareProcessNamespace: true

      #################
      #               #
      #  NATS Server  #
      #               #
      #################
      terminationGracePeriodSeconds: 60
      containers:
      - name: nats
        image: registry.lenovo.com/base/nats:2.1.7-alpine3.11
        ports:
        - containerPort: 4222
          name: client
          hostPort: 4222
        - containerPort: 7422
          name: leafnodes
          hostPort: 7422
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        - containerPort: 7777
          name: metrics
        command:
         - "nats-server"
         - "--config"
         - "/etc/nats-config/nats.conf"

        # Required to be able to define an environment variable
        # that refers to other environment variables.  This env var
        # is later used as part of the configuration file.
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_ADVERTISE
          value: $(POD_NAME).nats.$(POD_NAMESPACE).svc
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nats-config
          - mountPath: /etc/edge-nats-server-tls
            name: edge-nats-server-tls
          - mountPath: /etc/nats-streaming-leaf-tls
            name: nats-streaming-leaf-tls
          - name: pid
            mountPath: /var/run/nats

        # Liveness/Readiness probes against the monitoring
        #
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5

        # Gracefully stop NATS Server on pod deletion or image upgrade.
        #
        lifecycle:
          preStop:
            exec:
              # Using the alpine based NATS image, we add an extra sleep that is
              # the same amount as the terminationGracePeriodSeconds to allow
              # the NATS Server to gracefully terminate the client connections.
              #
              command: ["/bin/sh", "-c", "/nats-server -sl=ldm=/var/run/nats/nats.pid && /bin/sleep 60"]
